### ISSUE TITLE
installing trm-doppler: gcc error

### ISSUE THREAD

**Issue by aarranshaw** [trmrsh/trm-doppler#2]
<img width="1252" alt="doppler-error" src="https://user-images.githubusercontent.com/18578007/37624126-b15e080a-2b8c-11e8-9741-60892e8c068e.png">

Hi Tom, I'm trying to install the python version of Doppler on my machine. I've successfully done it in the past on a linux machine, and even published using it. However, that was a few years ago and now I'm on a Mac. I've successfully done all the hard stuff, i.e. pgplot. I've managed to install a bunch of your cpp packages, as well as the python version of trm-subs and trm-sla with no issues whatsoever. I've even installed molly successfully and use it regularly. 

However, I'm getting the attached output from setup.py for trm-doppler. Do you possibly have any insight on this? I have the prerequisites - cpp-mem and fftw, but I'm getting gcc errors which I don't understand. Hopefully you are able to help or point me in the direction of a Mac user who can help.

Cheers

Aarran

**Comment by trmrsh** [comment]
Hi Aarran, this is because the C++ compiler on Macs does not support not *= as an operation on the fftw_complex data type for some reason. Tariq Shahbaz had the same issue when he and I were on La Palma in February I think. You might want to contact him for his version of doppler.cc. I would be reasonably certain that the fixes we made on La Palma would also work on linux, so if you get it and want it in the code base, please fork trm-doppler on github and submit a pull request.

**Comment by aarranshaw** [comment]
Thank you Tom. I have gotten in touch with Tariq, and will close this issue when he gets back to me. Thanks again!

**Comment by aarranshaw** [comment]
Solved, will fork and create pull request with Tariq's fix. Thank you!
